# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages
notifications:
  email: false
 
before_install:
  - cd CrossVA

matrix:
  include:
  - r: devel
  - r: release
##    r_github_packages: verbal-autopsy-software/InSilicoVA/InSilicoVA
